baseURL = "https://www.grbavacigla.tk/"
languageCode = "en-us"
title = "Aleksa Ognjanovic"
theme = "hugo.386"
publishdir = ".."

[params]
    mainpagetitle = "Aleksa Ognjanovic"
    mainpagesubtitle = "Welcome to my personal website!"
    mainpagedesc = ""

    copyrightname = "Aleksa Ognjanovic"
    copyrighturl = ""
    showhugo = true
    github = "https://github.com/GrbavaCigla"
    
    loadfastload = false
    loadspeedfactor = 2.0
    loadonepass = false

[params.copyright]
    name = "Akeksa Ognjanovic"
    suffix = "[HUGO.386](https://gitlab.com/maxlefou/hugo.386)"

[menu]
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

